INFERENCE_GEMMA_ENGLISH_COLLEGE_PHYSICS_PATH = '../Infrence_Output/Gemma27B (English)/college_physics_flags.json'
INFERENCE_GEMMA_ENGLISH_HIGH_SCHOOL_PHYSICS_PATH = '../Infrence_Output/Gemma27B (English)/high_school_physics_flags.json'
INFERENCE_GEMMA_ENGLISH_STATIC_PHY_PATH = '../Infrence_Output/Gemma27B (English)/static_phy_flags.json'
INFERENCE_GEMMA_ENGLISH_PHYSICS_QA_PATH = '../Infrence_Output/Gemma27B (English)/PhysicsQA_flags.json'
INFERENCE_LLAMA_ENGLISH_COLLEGE_PHYSICS_PATH = '../Infrence_Output/Llama3_70B (English)/college_physics_flags.json'
INFERENCE_LLAMA_ENGLISH_HIGH_SCHOOL_PHYSICS_PATH = '../Infrence_Output/Llama3_70B (English)/high_school_physics_flags.json'
INFERENCE_LLAMA_ENGLISH_STATIC_PHY_PATH = '../Infrence_Output/Llama3_70B (English)/static_phy_flags.json'
INFERENCE_LLAMA_ENGLISH_PHYSICS_QA_PATH = '../Infrence_Output/Llama3_70B (English)/PhysicsQA_flags.json'